---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: maven
    tag: 3.6.2-jdk-12

inputs:
- name: reflection-code

outputs:
- name: artifacts

caches:
  - path: reflection-code/.m2/

run:
  path: ci/build.sh
  dir: reflection-code